# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/DNNv4/dnn_690t/dnn_690t.srcs/sources_1/ip/FIFO_W96_D512/FIFO_W96_D512.xci
# IP: The module: 'FIFO_W96_D512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/DNNv4/dnn_690t/dnn_690t.srcs/sources_1/ip/FIFO_W96_D512/FIFO_W96_D512.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_W96_D512'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/DNNv4/dnn_690t/dnn_690t.srcs/sources_1/ip/FIFO_W96_D512/FIFO_W96_D512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_W96_D512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/DNNv4/dnn_690t/dnn_690t.srcs/sources_1/ip/FIFO_W96_D512/FIFO_W96_D512.xci
# IP: The module: 'FIFO_W96_D512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/DNNv4/dnn_690t/dnn_690t.srcs/sources_1/ip/FIFO_W96_D512/FIFO_W96_D512.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_W96_D512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/DNNv4/dnn_690t/dnn_690t.srcs/sources_1/ip/FIFO_W96_D512/FIFO_W96_D512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_W96_D512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
