# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/DNN_IP/DNNv4/dnn_690t/dnn_690t.srcs/sources_1/ip/bram32_512/bram32_512.xci
# IP: The module: 'bram32_512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/DNN_IP/DNNv4/dnn_690t/dnn_690t.srcs/sources_1/ip/bram32_512/bram32_512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram32_512'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/DNN_IP/DNNv4/dnn_690t/dnn_690t.srcs/sources_1/ip/bram32_512/bram32_512.xci
# IP: The module: 'bram32_512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/DNN_IP/DNNv4/dnn_690t/dnn_690t.srcs/sources_1/ip/bram32_512/bram32_512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram32_512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
