# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/IO.xdc

# IP: ip/ExpROM/ExpROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ExpROM || ORIG_REF_NAME==ExpROM} -quiet] -quiet
