# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.cache/wt [current_project]
set_property parent.project_path /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/hht/gzb/DNN330/ppa/pp717/uart_ddr1/IPfor690t [current_project]
update_ip_catalog
set_property ip_output_repo /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/bias_dao_1127.coe
add_files /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/VLIW_504_256k.coe
add_files /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/exp.coe
read_verilog -library xil_defaultlib {
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/NMS.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/box_iou.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/buffer_pool.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/comp_tree.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/confidence_screen.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/decode_unit.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/delay_data.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/delay_vaild.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/exponent.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/output_buffer.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/position_resolution.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/postpro_FSM.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/read_cache_decode_pos.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/requant.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/sigmoid.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/sp_pe_unit.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/sys_rst.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/write_cache_pool.v
  /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/new/yolo_layer_top.v
}
read_ip -quiet /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/ip/ExpROM/ExpROM.xci
set_property used_in_implementation false [get_files -all /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/ip/ExpROM/ExpROM_ooc.xdc]

read_ip -quiet /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/ip/bram32_512/bram32_512.xci
set_property used_in_implementation false [get_files -all /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/ip/bram32_512/bram32_512_ooc.xdc]

read_ip -quiet /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/ip/div_gen/div_gen.xci
set_property used_in_implementation false [get_files -all /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/ip/div_gen/div_gen_ooc.xdc]

read_ip -quiet /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/ip/FIFO_W96_D512/FIFO_W96_D512.xci
set_property used_in_implementation false [get_files -all /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/ip/FIFO_W96_D512/FIFO_W96_D512.xdc]
set_property used_in_implementation false [get_files -all /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/ip/FIFO_W96_D512/FIFO_W96_D512_ooc.xdc]

read_ip -quiet /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/constrs_1/new/IO.xdc
set_property used_in_implementation false [get_files /home/hht/gzb/DNN330/ppa/pp717/dnn_690t/dnn_690t.srcs/constrs_1/new/IO.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top yolo_layer_top -part xc7vx690tffg1761-2 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef yolo_layer_top.dcp
create_report "synth_3_synth_report_utilization_0" "report_utilization -file yolo_layer_top_utilization_synth.rpt -pb yolo_layer_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
