set_property PACKAGE_PIN AK34 [get_ports diff_clock_rtl_clk_p]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports diff_clock_rtl_clk_p]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports diff_clock_rtl_clk_n]
set_property PACKAGE_PIN F36 [get_ports {DDR2_addr[13]}]
set_property IOSTANDARD SSTL18_II [get_ports {DDR2_addr[13]}]
